### ISSUE TITLE
How to get video features

### ISSUE THREAD

**Issue by ltp1995** [syuqings/video-paragraph#1]
Thank you for your repo. Could you please tell me how can I get i3d.flow, i3d.rgb and resnet200 features of untrimmed videos?

**Comment by syuqings** [comment]
Hi, we have uploaded the pre-extracted i3d.flow, i3d.rgb and resnet200 features of ActivityNet dataset to the BaiduNetdisk. They are extracted per 64 frames of the video.

**Comment by ltp1995** [comment]
> Hi, we have uploaded the pre-extracted i3d.flow, i3d.rgb and resnet200 features of ActivityNet dataset to the BaiduNetdisk. They are extracted per 64 frames of the video.

I need to extract above three kind of features on my customized video dataset, and now flow and rgb features have been extracted, but i was not sure about the method of resnet200 feature extraction.
Can you provide the pretrained models and some public references of resnet200 extraction to us?  For fair comparision with same feature types. Thanks!

**Comment by syuqings** [comment]
Hi, I have uploaded the script of resnet200 feature extraction in the resnet200/ folder, and you can download the pretrained model from the [BaiduNetdisk](https://pan.baidu.com/s/1xznBbIELY8Pp5N-98fiqdQ) (code:it7g).

**Comment by ltp1995** [comment]
> Hi, I have uploaded the script of resnet200 feature extraction in the resnet200/ folder, and you can download the pretrained model from the [BaiduNetdisk](https://pan.baidu.com/s/1xznBbIELY8Pp5N-98fiqdQ) (code:it7g).

Got it, thanks for your kind reply!

**Comment by ltp1995** [comment]
> > Thank you for your repo. Could you please tell me how can I get i3d.flow, i3d.rgb and resnet200 features of untrimmed videos?
> 
> hi! it seems like you have already solved the problem,can you show me the way to organize the features?i want to test this model by self video,hoping for your reply!

Hi, my i3d features are extracted from https://github.com/v-iashin/video_features/tree/4fa02bd5c5b8c34081dcfb609e2bcd5a973eaab2, and resnet200 feature extraction script is in the resnet200/ folder of this respository.
