### ISSUE TITLE
关于解码

### ISSUE THREAD

**Issue by yangjiangeyjg** [syuqings/video-paragraph#10]
作者您好，我想问一下解码的时候为什么输入只有前一步生成的单词，而不是像Transformer那样输入之前生成的所有单词，谢谢！
@syuqings

**Comment by syuqings** [comment]
Hi，因为在解码的时候代码存了之前所有单词的各层hidden，在计算self-attention时直接从cache中读取之前的context，并将当前时刻的hidden也加入到cache中。如果不进行存储，就需要将所有单词都输入，每次重新计算之前单词的hidden state用于self-attention层。

**Comment by yangjiangeyjg** [comment]
> Hi，因为在解码的时候代码存了之前所有单词的各层hidden，在计算self-attention时直接从cache中读取之前的context，并将当前时刻的hidden也加入到cache中。如果不进行存储，就需要将所有单词都输入，每次重新计算之前单词的hidden state用于self-attention层。

好的谢谢！
