### ISSUE TITLE
ResNet model

### ISSUE THREAD

**Issue by avinashsai** [syuqings/video-paragraph#11]
Hi,
Congratulations on the excellent work. I am unable to download resnet model from https://pan.baidu.com/s/1xznBbIELY8Pp5N-98fiqdQ#list/path=%2F. It is asking for user information. Can you upload this model on google drive or another alternate place?

Thanks in advance.

**Comment by syuqings** [comment]
Hi, the ResNet200 model has been uploaded to google drive https://drive.google.com/file/d/1nyf3JcJ2x90-LRAuhjlZbnc81zBjtWHs/view?usp=sharing.

**Comment by avinashsai** [comment]
Thank you!
