### ISSUE TITLE
pretrained.th 

### ISSUE THREAD

**Issue by ZHONGHZONG** [syuqings/video-paragraph#4]
Dear professor syuqings,

Strictly follow REDME ,In the third step of the training,Why was the post-training assessment not as high as the second-training model?Am I loading and training the pretrained.th the wrong way?

Looking forward to your reply

**Comment by syuqings** [comment]
Hi, I'm sorry to make the confusion. Actually, there are two training stages in total, not three.
The first stage is trained with the cross-entropy. In this stage, you can choose to train the model with full video frames (step 1 in the readme), or train the model with only key frames (step 3 in the readme).
The second stage is fine-tuning the model in the first stage with rl.

In the normal setting, you don't need to perform the step 3 in the readme.
I will update the readme to avoid the confusion.

**Comment by ZHONGHZONG** [comment]
Dear professor syuqings,
Thank you for your reply，May you happy every day！
