### ISSUE TITLE
Use self video to test

### ISSUE THREAD

**Issue by duanqipeng** [syuqings/video-paragraph#5]
hi ,thanks to your work on video2paragraph, could you tell me how to use my video to get the paragraph?

**Comment by duanqipeng** [comment]
thanks for your reply！is there any pipline or code in this repository to extract the i3d and resnet200 features?or maybe you can show me where i can find the solution

**Comment by duanqipeng** [comment]
i see the code resnet200_video.py in the folder resnet200/,is the extractor for the video?i don't know the way to extract and orgainze the i3d and resnet200 features-_-..

**Comment by duanqipeng** [comment]
> Yes, please see the issue #1.

well,i see the answer in issue1, and i know how to extract resnet200 feature by using your model.
But i am still not sure how to extract i3d features and how to organize both resnet200 and i3d feature,beacuse i find the dataset is organized by three part as :flow,rgb,resnet200, but when evaluation ,there is only an ae_test.npy, does it need to merge the three feature in one npy file?

**Comment by syuqings** [comment]
The ae_test.npy is just the name file. The three features will be concatenated automatically in readers/caption_data.py.
Therefore, just putting the extracted features in the corresponding feature folders is ok.
To extract the i3d.rgb and i3d.flow, see https://github.com/deepmind/kinetics-i3d please.

**Comment by syuqings** [comment]
当然如果你的视频是原数据集内的，由于特征已经抽好，在inference阶段不需要重新抽特征。而我理解你的视频是数据集之外的新视频，那就需要对他们抽取特征。
