### ISSUE TITLE
Sorry to be a bother

### ISSUE THREAD

**Issue by 123456789live** [syuqings/video-paragraph#6]
Dear professor syuqings,

 Sorry to be a bother，I read your paper titled and I am very interested in it. Strictly follow REDME ,  I don't understand what pretrained.th do？ Does pretrained.th have to be used to achieve the result of the author's article?

 I will be appreciated for your reply as soon as possible, thank you very much! 

Best regards,

**Comment by syuqings** [comment]
Hi, thank you for your interest.
The pretrained.th is a pretrained retrieval model, which is used for the video key-frame selection.
We provide two versions of our model. One is trained with all the video frames as previous works, and the other one is trained with key frames for efficiency. While the latter performs slightly worse than the full model but more quickly in the inference phase.
If you want to train the best model, the pretrained.th checkpoint is not necessary.

**Comment by 123456789live** [comment]
Dear professor syuqings,

Thank you very much for your reply. I am very happy. Thank you very much.

After your careful solution, solved my training problem. Now there's another question, why is it that when evaluate, the generated captions (corresponding to the name file in the public_split) I did not see the updated subtitles. Path. json The path is correct. .npy files open with messy letters.  Why is that?  How do you visualize the results?  

Sorry to be a bother，I will be appreciated for your reply as soon as possible, thank you very much! 

Best regards,

尊敬的syuqings教授，
非常感谢您的回信，特别开心，非常感谢您。经过您的细心解答，解决了我的训练问题。
目前又遇到了一个问题，为什么评估的时候，public_split没有看到更新的字幕（.npy文件的日期没有更新），path.json路径是正确的。.npy文件打开也都是乱的字母。这是为什么呢？怎么可视化结果呢?
打扰您了，非常非常抱歉，能得到您的回复不甚感激，期待您的回信。

**Comment by syuqings** [comment]
Did you evaluate the model as the instruction of Evaluation section in the README?
The generated captions are only saved when the test() function is called. In other words, the validation in the training phase won't save the results.
The generated result are saved in the "results\/\*\/folder\/pred\/tst\/" or "results\/\*\/folder\/pred\/val\/" folder, it is a json file.

**Comment by 123456789live** [comment]
Thank you very much for your reply,Sorry to be a bother,I get it.be thankful.May you enjoying your days!
